---
- name: Install Calico CRDs
  ansible.builtin.command:
    cmd: kubectl apply --server-side -f https://raw.githubusercontent.com/projectcalico/calico/v3.32.1/manifests/v1_crd_projectcalico_org.yaml
  become: false
  changed_when: true

- name: Install Tigera Operator
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.32.1/manifests/tigera-operator.yaml
  become: false
  changed_when: true

- name: Create Calico configuration
  ansible.builtin.copy:
    dest: /tmp/calico-installation.yml
    content: |
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          ipPools:
            - cidr: 10.244.0.0/16
              encapsulation: VXLANCrossSubnet
              natOutgoing: Enabled
              nodeSelector: all()
    mode: "0644"

- name: Apply Calico configuration
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/calico-installation.yml
  become: false
  changed_when: true
