---
- name: Check if Helm is installed
  ansible.builtin.command:
    cmd: helm version
  register: helm_check
  failed_when: false
  changed_when: false

- name: Download Helm installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755"
  when: helm_check.rc != 0

- name: Install Helm
  ansible.builtin.command:
    cmd: /tmp/get_helm.sh
  when: helm_check.rc != 0
