---
- name: Disable swap now
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap after reboot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s+.*)$'
    replace: '# \1'

- name: Load br_netfilter
  ansible.builtin.command: modprobe br_netfilter

- name: Load br_netfilter after reboot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/kubernetes.conf
    content: |
      br_netfilter
    mode: "0644"

- name: Configure Kubernetes network settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    mode: "0644"

- name: Apply Kubernetes network settings
  ansible.builtin.command: sysctl --system

- name: Install Kubernetes repository requirements
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true

- name: Add Kubernetes repository key
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key |
    gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /
    mode: "0644"

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
